version: "3"
services:
  dns-server:
    hostname: dns-server
    image: technitium/dns-server:latest
    # Use "host" network mode for DHCP deployments
    # network_mode: "host"
    ports:
      - "5380:5380/tcp" #DNS web console
      - "53:53/udp" #DNS service
      - "53:53/tcp" #DNS service
    environment:
      - DNS_SERVER_DOMAIN=dns-server #The primary domain name used by this DNS Server to identify itself.
    volumes:
      - config
    restart: always
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000

  proxy:
    build:
      context: .docker/haproxy/
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8404:8404"
      - "2222:2222"
    volumes:
      - certificates:/usr/local/etc/haproxy/certificates:ro

 
volumes:
    config:
    haproxy:
    certificates:

networks:
  default: